### ISSUE TITLE
Pool does not hold more than one event's random data at a time

### ISSUE THREAD

**Issue by nickpts** [smithc/Fortuna#2]
Looking at the source code in Pool.cs, I see that a new hash is computed every time event data is added, so this means the pool can only hold one event's data a time. 

However, the spec in Cryptography Engineering (2010), page 149 says: "Each random event is appended to the string in the pool in question". So I assume a pool must hold random data from multiple sources. 

Please clarify if I am missing something.

**Comment by smithc** [comment]
Hi @nickpts ,

Thank you for brining this to my attention.  I've reviewed the code, and you are absolutely correct.  The current implementation was based on a faulty assumption as to how .NET was computing its hashes.

To avoid storing potentially large strings of data in each of the pools, I desired to use the underlying hashing function in an incremental fashion, retrieving the results of the hash state between progressive hash computations.  As it turns out, this is not how the built-in .NET hashing functions work; the underlying hash state is inaccessible between invocations to `ComputeHash`, and the act of observing the hash output is destructive, resetting the state.

I have pushed up a quick prototype of a solution that attempts to preserve an incremental hashing approach, which you can find here: https://github.com/smithc/Fortuna/compare/bugfix/entropy-pool-proto-1?expand=1

In lieu of actually storing all entropy generated by a source, and hashing over the entire string, this proposal attempts to use the SHA256 hashing function in 'Counter (CTR) mode', which attempts to approximate incremental hashing by prepending the result of previous hashing computations to the input of the next hashing operation.

I believe that this would provide sufficient entropy for the purposes of providing pooled data, however just because I am not aware of any underlying weakness in the system does not mean that it does not exist, so I would appreciate any input you may have on this approach.

**Comment by nickpts** [comment]
Yes, good idea. It keeps the pools to fixed size while maintaining entropy.

**Comment by smithc** [comment]
This has now been merged: https://github.com/smithc/Fortuna/pull/3
