### ISSUE TITLE
AccumulateEntropy adds event data to one pool at a time

### ISSUE THREAD

**Issue by nickpts** [smithc/Fortuna#4]
Hi @smithc ,

I think there may be an issue with the AccumulateEntropy function. It seems to be called via callback every time a new event is available, however it only adds it to one pool at a time? 

According to the spec (9.5.2 Pools) "each source distributes its random events over the pools in a cyclical fashion". Unless I am missing something, I would expect to see a loop here.

**Comment by smithc** [comment]
Hi @nickpts,

The specification is somewhat vague on details here, so I took a few liberties on the implementation, while still trying to retain the spirit of the document.

In essence, the AccumulateEntropy function does indeed distribute incoming random event data into multiple pools in a cyclical fashion, but as you pointed out, it only does this once per pool, per event.  The key here is that the 'random distribution' of event data occurs via a 'round-robin' algorithm of pool selection, and this is accomplished by keeping track of the running total of raised events, and using that to select the next pool to inject data into on each raised event.

So I believe the AccumulateEntropy function is working as intended, in that we are injecting event data into all of the pools, but it does not guarantee uniform distribution of event data *from a particular source*, which I can see being different interpretation of the specification.

**Comment by nickpts** [comment]
Thanks @smithc. If possible, could you explain the advantages of such an implementation? 
Just trying to understand if I can improve mine.

**Comment by smithc** [comment]
@nickpts, apologies for the delay.  The primary advantage is the time-complexity of the operation.  Since we're just keeping track of the running count of raised events and injecting data into a single pool per event, the operation completes in O(C) time - it's constant.  On the other hand, if we want to ensure we distribute all source data uniformly across all pools, we need to loop through all of the pools, leading to an O(N) (or linear) time complexity for the operation.

Since this operation occurs for every raised event, the amount of processing required can really add up, especially given a large number of pools.  That said, as with all optimizations, I would recommend that you measure the performance characteristics of your own implementation, and decide for yourself whether or not that's a problem.

**Comment by nickpts** [comment]
Excellent, thank you.
